cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --account=HENDERSON-SL3-CPU
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name={rule}-{wildcards}
    --output=logs/{rule}/{wildcards}-%j.log
default-resources:
  - partition=icelake
  - mem_mb=3380
  - time="12:00:00"
restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: False
rerun-incomplete: False
printshellcmds: True
#scheduler: greedy
