#  mamba env create --name python_3.9.6 --file python_3.9.6_environment.yaml 
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.9.6
  - snakemake
  - biopython
  - pandas
  - numpy
  - scipy
  - matplotlib
  - matplotlib-venn
  - venn
  - seaborn
  - pysam
  - pybedtools
  - pyranges
  - mmh3
  - screed
  - scikit-bio
  - joblib
  - numba
  - r-base=4.1.0
  - r-essentials
  - r-ggplot2
  - r-doparallel
  - r-rcppparallel
  - r-parallelmap
  - r-dplyr
  - r-seqinr
  - r-stringr
  - r-svMisc
  - r-argparse=2.0.4
  - r-circlize
  - r-rmpi
  - r-doparallel
  - r-dofuture
  - r-dorng
  - r-future.batchtools
  - r-rcpp
  - r-gridbase
  - r-viridis
  - r-cairo # must be installed for complexheatmap to work (conda installation doesn't fix this so run install.packages("Cairo") in an interactive R session after running conda activate python_3.9.6 )
  - bioconductor-msa
  - bioconductor-biostrings
  - bioconductor-dmrcaller=1.24.0
  - bioconductor-rtracklayer=1.52.0
  - bioconductor-complexheatmap
  - bioconductor-segmentseq
  - bioconductor-regioner
  - bedtools=2.30.0
  - bbmap=38.98
  - winnowmap=2.03
  - minimap2=2.24
  - bwa=0.7.17
  - bowtie2=2.4.5
  - bowtie=1.3.1
  - samtools=1.15.1
  - rename
