#!/bin/bash

###sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array01of07_slurm && sleep 2;
###sbatch not_centromere_Chr2_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array01of05_slurm && sleep 2;
###sbatch not_centromere_Chr3_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array01of05_slurm && sleep 2;
###sbatch not_centromere_Chr4_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array01of06_slurm && sleep 2;
###sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array01of08_slurm && sleep 2;

##sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of07_slurm && sleep 2;
##sbatch not_centromere_Chr2_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of05_slurm && sleep 2;
##sbatch not_centromere_Chr3_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of05_slurm && sleep 2;
##sbatch not_centromere_Chr4_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of06_slurm && sleep 2;
##sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of08_slurm && sleep 2;

##sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of07_slurm && sleep 2;
##sbatch not_centromere_Chr2_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of05_slurm && sleep 2;
##sbatch not_centromere_Chr3_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of05_slurm && sleep 2;
##sbatch not_centromere_Chr4_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of06_slurm && sleep 2;
##sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of08_slurm && sleep 2;

sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array04of07_slurm && sleep 2;
sbatch not_centromere_Chr2_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array04of05_slurm && sleep 2;
sbatch not_centromere_Chr3_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array04of05_slurm && sleep 2;
sbatch not_centromere_Chr4_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array04of06_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array04of08_slurm && sleep 2;

sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array05of07_slurm && sleep 2;
sbatch not_centromere_Chr2_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array05of05_slurm && sleep 2;
sbatch not_centromere_Chr3_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array05of05_slurm && sleep 2;
sbatch not_centromere_Chr4_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array05of06_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array05of08_slurm && sleep 2;

sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array06of07_slurm && sleep 2;
sbatch not_centromere_Chr4_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array06of06_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array06of08_slurm && sleep 2;

sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array07of07_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array07of08_slurm && sleep 2;

sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array08of08_slurm && sleep 2;
