#!/bin/bash

sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array01of08_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of08_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of08_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array04of08_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array05of08_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array06of08_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array07of08_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array08of08_slurm && sleep 2;
