#!/bin/bash

sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of07_slurm && sleep 2;
sbatch not_centromere_Chr2_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of05_slurm && sleep 2;
sbatch not_centromere_Chr3_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of05_slurm && sleep 2;
sbatch not_centromere_Chr4_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of06_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of08_slurm && sleep 2;

sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of07_slurm && sleep 2;
sbatch not_centromere_Chr2_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of05_slurm && sleep 2;
sbatch not_centromere_Chr3_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of05_slurm && sleep 2;
sbatch not_centromere_Chr4_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of06_slurm && sleep 2;
sbatch not_centromere_Chr5_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of08_slurm && sleep 2;
