#!/bin/bash

sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array01of07_slurm && sleep 2;
sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array02of07_slurm && sleep 2;
sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array03of07_slurm && sleep 2;
sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array04of07_slurm && sleep 2;
sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array05of07_slurm && sleep 2;
sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array06of07_slurm && sleep 2;
sbatch not_centromere_Chr1_hybrid_read_segments_acc_chr_specific_kmers_py_icelake_array07of07_slurm && sleep 2;
